language: python

python :
  - "2.7"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script :
  - python tests.py
  - coveralls
  - flake8

after_script:
  - coveralls